import math
from typing import Dict, Any, List, Optional
from pydantic import BaseModel
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from backend.app.database import get_db
from backend.app.api.plans import run_optimized_plan, _LATEST_OPTIMIZED_PLAN

router = APIRouter(prefix="/kavach", tags=["Kavach (TCAS) & Electronic Interlocking TSR Simulator"])


class KavachSimulationRequest(BaseModel):
    train_no: str = "12004"
    train_name: str = "Lucknow Shatabdi Express"
    initial_speed_kmh: float = 120.0
    driver_braking_applied: bool = False
    block_id: Optional[str] = None


@router.get("/tsr-feed")
def get_kavach_tsr_feed(db: Session = Depends(get_db)) -> Dict[str, Any]:
    """
    Returns live Digital Temporary Speed Restriction (TSR) profiles generated by SETU
    ready for radio transmission to on-board locomotive Kavach (TCAS) units.
    """
    global _LATEST_OPTIMIZED_PLAN
    if _LATEST_OPTIMIZED_PLAN is None:
        _LATEST_OPTIMIZED_PLAN = run_optimized_plan(db=db)

    tsr_profiles = []
    for idx, block in enumerate(_LATEST_OPTIMIZED_PLAN.blocks[:6]):
        # Station kilometer mapping
        start_km = 22.400 + (idx * 35.2)
        end_km = start_km + 3.800
        sec_name = block.section_id or "NDLS - GZB"

        tsr_profiles.append({
            "tsr_id": f"TSR-NR-DLI-{block.block_id}",
            "block_id": block.block_id,
            "section_id": sec_name,
            "track_type": "DN MAIN" if idx % 2 == 0 else "UP MAIN",
            "start_km": round(start_km, 3),
            "end_km": round(end_km, 3),
            "length_km": 3.8,
            "caution_speed_kmh": 30,
            "normal_line_speed_kmh": 130,
            "reason": "Post-Tamping Ballast Consolidation (IRPWM Para 807)",
            "effective_duration_hours": 48,
            "rfid_tag_boundary_inrear": f"RFID-NR-KM-{int(start_km)-1}-400",
            "rfid_tag_boundary_inadvance": f"RFID-NR-KM-{int(end_km)+1}-100",
            "stationary_kavach_unit": f"STU-{sec_name.split('-')[0].strip()}-RRI-01",
            "tcas_packet_hex": f"0x4B 0x41 0x56 0x0{idx+1} 0x1E 0x82 0xFF",
            "transmission_status": "BROADCASTING_ON_UHF_457MHZ",
            "target_locomotives_in_section": ["WAP-7 #30214 (12004 Shatabdi)", "WAP-5 #30012 (12424 Rajdhani)"],
        })

    return {
        "status": "ONLINE",
        "system": "Indian Railways Kavach (TCAS) Radio Transmission Gateway",
        "frequency": "457.125 MHz UHF Duplex",
        "active_tsrs_count": len(tsr_profiles),
        "tsr_profiles": tsr_profiles,
        "interlocking_integration": "Electronic Interlocking (EI) Form S&T-T/351 Auto-Synced",
    }


@router.post("/simulate-intervention")
def simulate_kavach_intervention(req: KavachSimulationRequest) -> Dict[str, Any]:
    """
    Simulates approaching locomotive cab dynamics against the active SETU TSR restriction zone.
    Demonstrates Kavach Automatic Emergency Brake (AEB) intervention when driver ignores caution.
    """
    tsr_speed_limit = 30.0  # km/h
    target_km = 22.400  # Start of track maintenance caution zone
    approach_start_km = 21.000  # Train starts 1.4 km in rear
    total_distance_m = (target_km - approach_start_km) * 1000  # 1400 meters

    initial_mps = req.initial_speed_kmh / 3.6
    target_mps = tsr_speed_limit / 3.6

    time_steps = []
    current_dist = 0.0
    current_speed_mps = initial_mps
    dt = 0.5  # half second time steps
    t = 0.0

    kavach_warning_active = False
    kavach_aeb_applied = False
    brake_cylinder_pressure = 0.0  # kg/cm²

    # Dynamic run
    while current_dist < total_distance_m and current_speed_mps > 0.1 and t < 60.0:
        dist_to_boundary = total_distance_m - current_dist

        if req.driver_braking_applied:
            # Compliant loco pilot applies service brake at 1,000m in rear
            if dist_to_boundary <= 1000.0:
                brake_cylinder_pressure = 2.4
                # Decelerate smoothly to target 30 km/h
                if current_speed_mps > target_mps:
                    current_speed_mps = max(target_mps, current_speed_mps - (0.65 * dt))
        else:
            # Non-compliant / distracted driver: Kavach supervisory curve takes over!
            if dist_to_boundary <= 850.0:
                kavach_warning_active = True  # Cab audio visual alert

            if dist_to_boundary <= 550.0:
                # Driver failed to brake: Kavach TCAS trips Automatic Emergency Brake (AEB)
                kavach_aeb_applied = True
                brake_cylinder_pressure = 3.8  # Full emergency brake application
                # Rapid emergency deceleration (1.25 m/s²)
                current_speed_mps = max(0.0, current_speed_mps - (1.25 * dt))

        current_dist += current_speed_mps * dt
        t += dt

        time_steps.append({
            "time_sec": round(t, 1),
            "distance_traveled_m": round(current_dist, 1),
            "distance_to_tsr_boundary_m": max(0.0, round(dist_to_boundary, 1)),
            "speed_kmh": round(current_speed_mps * 3.6, 1),
            "target_speed_kmh": tsr_speed_limit,
            "kavach_warning": kavach_warning_active,
            "kavach_aeb_active": kavach_aeb_applied,
            "brake_cylinder_pressure_kgcm2": brake_cylinder_pressure,
        })

    final_speed_kmh = round(current_speed_mps * 3.6, 1)
    safety_margin_m = max(0.0, round(total_distance_m - current_dist, 1))

    if req.driver_braking_applied:
        outcome_status = "DRIVER_COMPLIANT_SMOOTH_ENTRY"
        outcome_message = f"Loco Pilot applied regenerative service brake. Train entered {tsr_speed_limit} km/h caution zone smoothly."
    else:
        outcome_status = "KAVACH_AEB_INTERVENTION_SUCCESS"
        outcome_message = (
            f"Kavach TCAS detected driver overspeed ({req.initial_speed_kmh} km/h). "
            f"Automatic Emergency Brake deployed at 550m in rear. "
            f"Train halted safely {safety_margin_m}m BEFORE track possession crew zone with ZERO collision risk."
        )

    return {
        "train_no": req.train_no,
        "train_name": req.train_name,
        "driver_mode": "MANUAL_COMPLIANT" if req.driver_braking_applied else "DISTRACTED_OVERSPEED",
        "initial_speed_kmh": req.initial_speed_kmh,
        "final_speed_kmh": final_speed_kmh,
        "tsr_limit_kmh": tsr_speed_limit,
        "safety_margin_meters_before_block": safety_margin_m,
        "kavach_warning_sounded": kavach_warning_active or req.driver_braking_applied,
        "kavach_emergency_brake_engaged": kavach_aeb_applied,
        "outcome_status": outcome_status,
        "outcome_message": outcome_message,
        "telemetry_samples_count": len(time_steps),
        "trajectory_samples": time_steps[::3],  # Sampled for frontend smooth graph
    }
